### ISSUE TITLE
Re-create Directors Report

### ISSUE THREAD

**Issue by tcoma-ups** [CIMDBORG/CIMMigrationProject#102]
Re-create a Directors report of all open items being worked on - Issues, Defects, BCs, etc. Anything that is in an open status and is currently being worked on should be on this report.

**Comment by carrubba24** [comment]
I will be reworking the query for this, will likely schedule some time to get the data mapping if we want to add this to the DB. Since they are similar queries, I noticed the 'Export to Excel' function in the Report Screen is busted. I would like to use this opportunity to get that functional again since my applications are beginning to request a report weekly.
