### ISSUE TITLE
EDI Database - Spliting Customer Table into a Products and Companies Table

### ISSUE THREAD

**Issue by mikey2695** [CIMDBORG/CIMMigrationProject#15]
In the midst of building the EDI database, I have come to the realization that the customer table should be split into a company table and a product table. The reason for this is that a company can have many products, but a product only has one company. There is no reason to continue to fill out the "COMPANY_NAME" column over and over for the same company when adding to the customer table. My new Structure would have technical contacts in the product table (as those contacts are product-specific) and the company contacts should go in the company tables. 

I can elaborate during tomorrow's meeting, Jan-Marie, if need be.

**Comment by qdd8jtl** [comment]
I like the idea, Mike.  Let's run it by the EDI team (if you haven't already done so) at our meeting to make sure they are OK with the changes.

**Comment by milleniumchilld** [comment]
I split the tables and do a mock up.

**Comment by milleniumchilld** [comment]
Team, please see attached customer table and give me your thoughts. 
[Customer Table.docx](https://github.com/CIMDBORG/CIMMigrationProject/files/4105718/Customer.Table.docx)

**Comment by JohnAlapatt** [comment]
Is it Necessary to have the address for all the customers?  If necessary, we should have a drop down for State and Country.

John Alapatt ** UPS EDI small Package ** 201 828 3649


Confidentiality Notice: This message is intended exclusively for the individual or entity to which it is addressed. This communication may contain information that is proprietary, privileged, confidential or otherwise legally exempt from disclosure. If you are not the named addressee, you are not authorized to read, print, retain, copy or disseminate this message or any part of it. If you have received this message in error, please notify the sender immediately either by phone (201-828-3649) or reply to this e-mail and delete all copies of this message.
