### ISSUE TITLE
Starting the Commenting portion of the project

### ISSUE THREAD

**Issue by mortii09** [CIMDBORG/CIMMigrationProject#31]
Team, 

Per our conversation, the purpose of this issue is to Keep track of the specific page we are going to be commenting for the CIMMigrationProject. For starters, we will all take one page of thr .CS page and comment it out. 

**Very Important**, since we just made a new update.  Can we please have a person volunteer to update the code portion of this repository online? so we can all just download the page through here, and start pushing/pasting back. this way we are not going to be commenting any old or deleted work and we are all on the same page. 

We will post the page we will take care of after the full updated project upload to the repo.

**Comment by mikey2695** [comment]
Just updated @mortii09

**Comment by mortii09** [comment]
Thank you good sir @mikey2695

**Comment by Pawel062** [comment]
Hi Guys,

In order to keep this organized and to make sure we don't start commentating on something already in progress, I made a excel file with all the .cs, .config, and other filetypes we should comment on. If you choose to comment on a file please put your name on there and status even if not started yet. If there's any files I missed, have been commented already, or should be added then please update the list.

File location: ‪\\mornas2\CIM\Production\Mike Figueroa Issues Database Application\CAB_Databases_Status_of_Commentating.xlsx

Let me know if you have any questions or a better alternative than excel and the lan.

**Comment by mortii09** [comment]
that is great! beats my idea haha thank you

**Comment by tcoma-ups** [comment]
Closing this issue due to completion
